### ISSUE TITLE
Support for "youtu.be" urls?

### ISSUE THREAD

**Issue by jtbayly** [bcollin/yt-nocookie#2]
Hi there. I just attempted to use this on my site. I'm not sure, but it doesn't appear to be working.

1. Is there built-in support for videos embedded using this sort of url:?

https://youtu.be/GBqjy3kd3QM

2. How can I verify for sure whether this is working or not? I assumed that if it was working there wouldn't be calls to doubleclick.net until I clicked to play the video.

Oh. And thanks for making and releasing the plugin!

**Comment by bcollin** [comment]
1) No. It once did, but I added heavier filtering later on in order to make sure non-Youtube links would not get returned inside my iframe, and youtu.be support got lost in the process. 

I will see if I can put it back in.

2) No, all it does is not place Youtube cookies until the visitor clicks the player. 

If you are familiar with your browser's developer tools (generally, start by pressing F12), you can use those to find out if any cookies were set. 

Youtube calls this their 'privacy enhanced' mode, and although strictly speaking this is not untrue, even the privacy enhanced version of Youtube is quite privacy unfriendly. If you want something that protects visitors from all of Youtube's impertinences, you could look into plugins that either will replace a Youtube player by a different player or that postpones loading a player altogether, for example by replacing it by a Youtube thumbnail. [Lazy Load](https://wordpress.org/plugins/rocket-lazy-load/) is an example of a plugin that is the latter (or at least claims to be, I haven't tried it).

Thank you for your report.

**Comment by bcollin** [comment]
I have restored Youtu.be support. Please let me know if anything is still wrong.

**Comment by bcollin** [comment]
The regex also allows domains like youtube.comxxx and xxxyoutu.be, so that still needs to be fixed.
